### ISSUE TITLE
Add section to the Ember Style Guide related to component integration tests

### ISSUE THREAD

**Issue by notmessenger** [softlayer/ember-style-guide#29]
> Reference a component under test via `this.$( '>:first-child' )` rather than via a class name when appropriate, which is the majority of the time.  Not using a classname removes the too-tight coupling between the styling used and the functionality provided by the component.  This selector should also be used when attempting to find additional elements, such as a button, etc.

> When this is not always appropriate is when you are rendering multiple components and need to access ones beyond `first-child`.

**Comment by erangeles** [comment]
@notmessenger per this conversation in group chat, we have decided to use  `this.$( '>:first-child' ).find( 'input' )` , please see below on the conversation. This is a response to your "This selector should also be used when attempting to find additional elements, such as a button, etc." statement.


(2:00:36 PM) Aziz Punjani: Let's have a vote this.$( '>:first-child' ).find( 'input' )  vs this.$( '>:first-child input' )
(2:00:37 PM) erangeles: yeah thats what my train of thought was as well
(2:00:55 PM) erangeles: I vote for this.$( '>:first-child' ).find( 'input' )
(2:00:55 PM) mcarroll: I vote for the .find approach
(2:01:01 PM) Jeff Corley: .find
(2:01:15 PM) Aziz Punjani: I like .find( 'input' ) just because it's more verbose and easier to discern.
(2:01:21 PM) Jeff Corley: actually, i vote that michael change his code :D
(2:01:30 PM) mcarroll: no prob. 
(2:01:33 PM) Aziz Punjani: ^^ +1
(2:01:34 PM) mcarroll: changed
(2:01:45 PM) erangeles: so since we all voted on it, I'll make amends to the style guide then.
(2:01:52 PM) erangeles: to reflect that

**Comment by notmessenger** [comment]
`find()` should be used regardless of whether are selecting an element type (i.e. `span`) or via another selector (i.e. '.className')

**Comment by notmessenger** [comment]
**MUST**s

* Computed Properties
 * Test the use of this property in the component's template functions as expected.
 * Test that the correct properties are being observed and that the expected behavior occurs when they are modified
